# Podfile

platform :ios, '7.1'

pod 'SVProgressHUD', '~> 1.1'
pod 'AFNetworking', '~> 2.5.3'
pod 'Mantle', '~> 2.0'

target :TrovTestTests, :exclusive => true do
    pod 'Mantle', '~> 2.0'
  # pod 'Kiwi'
end
